#%RAML 0.8
---
title: uniwin API
baseUri: http://localhost:8080/uniwin
version: v1

#---method---
/v1:
  /styles:
    description: 款式相关接口
    get:
      description: 获取款式列表
      queryParameters:
        page:
          displayName: page
          type: integer
          example: 1
          required: true
          description: 页数从0开始
        num:
          type: integer
          example: 10
          required: true
          description: 每页多少项
        operation:
          type: string
          example: SEARCH/NORMAL
          required: true
        key:
          type: string
          example: 201674
          required: false
          description: 如果operation是SEARCH,该值就是要搜索的关键词
        field:
          type: string
          example: CODE|NAME
          description: 要搜索的域,域之间用|隔开
          required: false
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0失败1成功,
                  "data":{
                      "count":100,
                      "list":[{
                          "code":款号,
                          "imgUrl": 图片地址,
                          "description": 描述,
                          "pass":true或false
                          },{},...]
                  },
                  "error":{
                    "code":错误码,"message":错误信息
                  }
                }
    post:
      description: 新建款式
      queryParameters:
        code:
          type: string
          example: 20160606
          required: true
          description: 款号
        imgUrl:
          type: string
          example: http://asdf.com/
          required: true
          description: 图片地址，先上传到七牛云然后获取地址
        description:
          type: string
          example: asdfasdf
          required: true
          description: 描述
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0失败1成功,
                  "data":null,
                  "error":{
                    "code":错误码,"message":错误信息
                  }
                }
    put:
      description: 修改款式，提供所有修改过和未修改的信息
      queryParameters:
        number:
          type: string
          example: 20160606
          required: true
          description: 款号
        imgUrl:
          type: string
          example: http://asdf.com/
          required: true
          description: 图片地址，先上传到七牛云然后获取地址
        description:
          type: string
          example: asdfasdf
          required: true
          description: 描述
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0失败1成功,
                  "data":null,
                  "error":{
                    "code":错误码,"message":错误信息
                  }
                }
    delete:
      description: 删除款式
      queryParameters:
        code:
          type: string
          example: 20160606
          required: true
          description: 款号
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "result":0失败1成功,
                  "data":null,
                  "error":{
                    "code":错误码,"message":错误信息
                  }
                }
    /detail:
      description: 款式详情
      get:
          queryParameters:
            code:
              type: string
              example: 20160606
              required: true
              description: 款号
          responses:
            200:
              body:
                application/json:
                  example: |
                    {
                      "result":0失败1成功,
                      "data":{
                      "code":款号,
                      "imgUrl": 图片地址,
                      "description": 描述,
                      "pass":true或false,
                      "orderList":[
                      {
                      "id":10,
                      "state":状态描述
                      },{},...
                      ]
                      },
                      "error":{
                        "code":错误码,"message":错误信息
                      }
                    }
  /materials:
    description: 物料相关接口
    get:
      description: 获取物料信息

    post:
      queryParameters:
        password:
          displayName: password
          type: string
          example: 12345
          required: true
          description: 使用token加密
        userName:
          type: string
          example: abcd
          required: true
          description: 必须由字母数字组成
        sex:
          type: string
          example: 0(男),1(女)
          required: true
        birthday:
          type: string
          example: 2015-11-09,注意格式
          required: true
        schoolId:
          type: number
          example: 1
          required: true
        departmentId:
          type: number
          example: 1
          required: true
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "data":{
                    "result":0(表示失败,用户名重复),非0(表示userId)
                  },
                  "success": true,
                  "status": 200
                }
