#%RAML 0.8
title: RESTFUL API
baseUri: http://localhost:8080/uniwin/
mediaType: application/json
/announce:
  /getMyAnnounces:
    description: 消息,收到的通知
    get:
      queryParameters:
        page:
          displayName: page
          type: number
          example: 0
          required: false
          description: 默认是0,从0开始
        num:
          displayName: num
          type: number
          example: 10(默认)
          required: false
          description: 需要获取的通知数量，可能返回的通知数量比它小
      responses:
        200:
          body:
            application/json:
              example: |
               {
                  "result":[{
                        "name": "用户名",
                        "id": 1(通知id),
                        "iconUrl": "用户头像url",
                        "time": "2015-11-29 00:00:00",
                        "content": "abcd(通知内容)",
                        "read": 是否已读,0表示未读,1表示已读
                       },{},{}...]

                }
  /getMyUnReadAnnounces:
    description: web ,消息,收到的未读的通知
    get:
      queryParameters:
        page:
          displayName: page
          type: number
          example: 0
          required: false
          description: 默认是0,从0开始
        num:
          displayName: num
          type: number
          example: 10(默认)
          required: false
          description: 需要获取的通知数量，可能返回的通知数量比它小
      responses:
        200:
          body:
            application/json:
              example: |
                {
                "data":{
                  "result":[{
                        "name": "用户名",
                        "id": 1(通知id),
                        "iconUrl": "用户头像url",
                        "time": "2015-11-29 00:00:00",
                        "content": "abcd(通知内容)"
                       },{},{}...]
                  "success": true,
                  "status": 200
                  }
                }
        401:
  /readAnnounce:
    description: 读通知，点击我的某一个通知时发的request
    get:
      queryParameters:
        id:
          type: integer
          required: true
          description: 通知id
      responses:
        200:
          body:
            application/json:
              example: |
                {

                  "result":0(表示失败),1(表示成功)


                }

  /getUnReadAnnounceNum:
    description: 获取未读通知的数量
    get:
      responses:
        200:
          body:
            application/json:
              example: |
               {
                  "result":0(数量)

                }


